### ISSUE TITLE
[Qualcomm feedback] 3.2.2. Platform Hardware Components - Hardware Root-of-Trust : PCIe accessible HROT requirement

### ISSUE THREAD

**Issue by jyao1** [riscv-non-isa/riscv-ap-tee-io#73]
Reference: https://lists.riscv.org/g/tech-ap-tee-io/topic/103498833#47

Why impose such functionality on an HROT while all the protocol complexity should be in TSM? Why do TSM and HROT must have an SPDM link in between them? The figure implies that

**Comment by sameo** [comment]
The idea behind that requirement is to keep the TSM implementation generic and not specific to any platform.

Unlike devices, RP IDE key management is not specified and each RISC-V platform may have its own protocol or interface for that. Having TSM directly support that means we would eventually have to support a growing list of vendor and hardware specific interfaces. On the other hand, RoTs are very much bound to the platform they running on and it seems reasonable to expect them to be able to program RP IDE keys using a platform specific interface. Moreover they are part of the TCB and can securely hold the IDE keys.

So if we want to keep the TSM implementation platform agnostic, have it generate and own the RP IDE keys but delegate the IDE key programming to the RoT, we need to find a way for the TSM to share those keys with the RoT. The PCIe IDE KM protocol is basically designed for that, and relies on SPDM and DOE for doing so.

So I don't think we're burdening the RoT with complexity, but rather preserving the TSM from carrying platform and vendor specific implementations.

**Comment by jyao1** [comment]
> So if we want to keep the TSM implementation platform agnostic, have it generate and own the RP IDE keys but delegate the IDE key programming to the RoT, we need to find a way for the TSM to share those keys with the RoT. The PCIe IDE KM protocol is basically designed for that, and relies on SPDM and DOE for doing so.

This is good justification.

Looking at PCIe spec, it allows IDE setup with IDE_KM or vendor specific way.
I think we should *allow* using both standard and vendor specific implementation.

**Comment by eckhard-delfs-qualcomm** [comment]
> So if we want to keep the TSM implementation platform agnostic, have it generate and own the RP IDE keys but delegate the IDE key programming to the RoT, we need to find a way for the TSM to share those keys with the RoT. The PCIe IDE KM protocol is basically designed for that, and relies on SPDM and DOE for doing so.

As stated, the propagation of TSM generated IDE keys to PCIe RP is not specified by PCIe. Introducing SPDM as mandatory secure communication vehicle between TSM and RoT may address the problem of platform agnostic TSM implementations but imposes substantial requirements on the RoT which now has to be able to support SPDM. SPDM is fairly new protocol, even more complex to design and verify than TLS. Many of the SPDM design objectives do not really apply for this link (TSM->RP), since here it is about securing a SoC- or platform internal communication path, as opposed to setting up a link from the TSM to an arbitrary device DSM connected via the PCIe network.
We therefore should allow for vendor specific implementations.

**Comment by sameo** [comment]
This is closed with https://github.com/riscv-non-isa/riscv-ap-tee-io/pull/105
